---
title: "06_model"
author: "s222498"
format: html
editor: visual
---

## Modelling of the data

Loading Libraries

```{r}
library(tidyverse)
library(broom)
library(dplyr)
library(purrr)
```

Load augmented data

```{r}
#loading augmentated data for modeling
lm_data <- read_csv("../data/augmented.csv")

```

Modelling using lm() function

```{r}
lm_data_nested <- lm_data %>%
  group_by(age_interval) %>%
  nest() %>%
  mutate(model_object <- map(.x = data ,
                      .f = ~lm(formula = chd~tobacco, data = .x)
                      ))%>%
  ungroup()

lm_data_nested |>
  filter(age_interval == "20-40") |>
  pull() |>
  pluck(1) |>
  tidy(conf.int = TRUE, conf.level = 0.95)
#lm_model <- lm(chd ~ tobacco + alcohol+obesity+age, data = lm_data)
```

Making the model data tidy

```{r}
lm_model |> tidy()
```

```{r}
summary(lm_model) 
```

Visualizing P value of the model

```{r}
lm_model |> 
  tidy() |> 
  ggplot(aes(x = term,
             y = -log10(p.value))) +
  geom_point() +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed")
```

Including the confidence intervals

```{r}
ci<- lm_model |> 
  tidy(conf.int = TRUE,
       conf.level = 0.95)
ci
```

Visualizing the confidence interval

```{r}
ci |> 
  ggplot(aes(x = estimate,
             y = term,
             xmin = conf.low,
             xmax = conf.high)) +
  geom_errorbarh(height = 0.1) +
  geom_point()
```
